version: '3.9'

services:
  infra_db:
    image: postgres
    container_name: infra_db
    ports:
      - 25432:5432
    restart: always
    volumes:
      - ${PWD}/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r

  infra_admin:
    image: adminer
    container_name: infra_admin
    restart: always
    ports:
      - 28080:8080

